---
title       : Fatalities and Injuries Due to Different Types Of Storms
subtitle    : 
author      : Shivang Agarwal
job         : 
framework   : io2012        # {io2012, html5slides, shower, dzslides, ...}
highlighter : highlight  # {highlight.js, prettify, highlight}
hitheme     : tomorrow      # 
widgets     : []            # {mathjax, quiz, bootstrap}
mode        : selfcontained # {standalone, draft}
knit        : slidify::knit2slides
github:
  user: gnavihs
  repo: SlidifyDemo
---

## Synopsis
> Storms and other severe weather events can cause public health problems for communities and municipalities. Many severe events can result in fatalities and injuries and preventing such outcomes to the extent possible is a key concern.

> This presentation explores the U.S. National Oceanic and Atmospheric Administration's (NOAA) storm database. This database tracks characteristics of major storms and weather events in the United States, including when and where they occur, as well as estimates of any fatalities and injuries.


--- .class #id 


## Shiny Application

I found out 7 most harmful storms and summarized the number of fatalities and injuries caused by them every year since 1992 in United States of America.
Here is a brief summary of the data:

```{r echo=F}
data <- read.csv("MyData.csv", header = TRUE, sep = ",", col.names = c("Year", "Event Type", "Fatalities", "Injuries"))
summary(data)
```

--- .class #id 

## Shiny Application
The app creates a bubble plot for fatalities versus year. Each type of storm is coloured differently. The size of the bubble indicates the number of people injured. Thus, making it a 4 dimensional plot. As you hit play on the slider, the year gets incremented and you can see the impact each year by each storm(given the data is available).


--- .class #id 

### Thank You!




